### ISSUE TITLE
ACP>the ACP menu should have links for the different pages

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix_plugins#12]
It's a bit annoying for now.

**Comment by vendethiel** [comment]
@MightyGorgon are you OK with force-enabling the ACP menu module?

**Comment by MightyGorgon** [comment]
Can you please clarify what do you mean? I don't understand...

**Comment by vendethiel** [comment]
Cash plugin has two acp mode:
 - the mod with links in the acp menu (like every other mod on earth)
 - the mod with "Cash configuration" that redirects to a page with the links

The second one was made back then because phpBB2 ACP didn't have html collapsing pre-installed.

Since we do have it on IP, i'd like to enable the lateral menu mode (first one) by default.

**Comment by vendethiel** [comment]
see #49
