### ISSUE TITLE
Trying to see the copyright page results in a "Hacking Attempt"

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix_plugins#15]
Clicking "© Activity Mod Plus"
opens a pop-up that says "Hacking Attempt"

**Comment by MWE001** [comment]
gave an answer over at Icy

**Comment by vendethiel** [comment]
@MWE001 usually, it's best to post a link here, so we can find it if we need to weeks or months or years later. Thanks!

**Comment by MWE001** [comment]
Ah ok man thats cool. I can do that. Thanks for the info. I will include links from now on. 

Do you guys prefer I post fixes here in the comments or post up over at Icy Phoenix?

**Comment by vendethiel** [comment]
You can open issues here!

This one has been fixed.
