### ISSUE TITLE
activity.php>"Games" section says "vote cast"

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix_plugins#17]
It says "vote cast" instead of saying "No votes cast", somehow.
See on the screen:

![](http://i.imgur.com/5NyqQTB.png)

Clicking on "rate this game" actually works.

In the other sections, as "newest games added", it displays correctly:

![](http://i.imgur.com/OLiRJXJ.png)

**Comment by MWE001** [comment]
I fixed this. it was an easy fix.  I will post over at Icy website since I am not sure how to use Git exactly.

**Comment by vendethiel** [comment]
@MWE001 thanks! You can post it here as well, or post a link to the topic.
