### ISSUE TITLE
[Activity] newscore.php should show layout

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix_plugins#19]
If the game has been played "in this window", newscore.php should show the IP layout;

(if the game has been played in a popup, it shouldn't)

**Comment by MWE001** [comment]
This has been fixed here http://www.icyphoenix.com/viewtopic.php?f=2&t=9623

**Comment by vendethiel** [comment]
Thanks!

**Comment by MWE001** [comment]
Not a problem at all man. that is what we are all here for.
