### ISSUE TITLE
[!][Cash] The config links don't have SID

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix_plugins#29]
**major breakage**

Basically, the links in "cash management" have **NO SID**.
So when you try to click them, you get redirected to IP's index instead...

**HOWEVER** the topbar menu works correctly.

**Comment by MWE001** [comment]
I think the dirty fix that Mort suggested works just fine. Is there really a need to have a nav bar up top and Menu horizontally as well on the very same page? That is kind of  redundant.

**Comment by vendethiel** [comment]
@MWE001 I'd even suggest we enable the ACP menu mode by default, and remove the option to switch it off..

**Comment by MWE001** [comment]
Yeah that would actually work better in my opinion.I don't mind the admin nav for FAP but on the cash mod it has always kind of bugged me (no pun intended).

**Comment by MWE001** [comment]
In order to do that though, one must do this fix that Luca gave to me in this thread http://www.icyphoenix.com/viewtopic.php?f=2&t=9623 Without that fix, the whole ACP menu is garbage. The links all went back to 404 pages. With The fix Luca gave me, my ACP menu works a treat.

**Comment by vendethiel** [comment]
[MG is ahead of you :P](https://github.com/MightyGorgon/icy_phoenix_plugins/commit/f717159e0b1998181d9b59dd34db02e9ba9af8e9#diff-d879574f1658ea9b1c85f4c653342c71R117)

**Comment by MWE001** [comment]
Nice! And actually thinking about it man, the cash mod has not 1, not 2 but 3 menus!  lol We could eliminate 2 of them an d only have one as it should be.

**Comment by vendethiel** [comment]
yes, I agree.

**Comment by MWE001** [comment]
I attempted to work on this tonight and all kinds of things went wrong real fast. I was able to remove the switch in the acp, and after that thing started going horribly wrong. I don't know where the switch is in the php file and how to set the acp up default to navbar instead of menu. I reverted my files back to morts quick dirty fix.
