### ISSUE TITLE
Links Block

### ISSUE THREAD

**Issue by MWE001** [MightyGorgon/icy_phoenix_plugins#45]
Template->make_filename(): Error - template file not found: blocks/plugin_links_block.tpl

I saw the links block added and was smiling ear to ear until I noticed no blocks tpl folder  lol

I'll disable the block for now. I am so glad to see you working on links block!

**Comment by vendethiel** [comment]
Looking at , let's se474370d0e117001e4a0868f43032b07d658ef262e if a file was "forgotten".

**Comment by vendethiel** [comment]
The file to salvage is [here](https://github.com/MightyGorgon/icy_phoenix/blob/df8a65bee23c929fdcb8e13d44d8c6ae43626b9d/templates/default/blocks/links_block.tpl).

@MightyGorgon Do we want to put the blocks in the `templates` directory, or do we want to add a `plugin` key to blocks?

**Comment by MWE001** [comment]
Nice catch. I had noticed at about 2L30 am my time that templates were being moved in to the defaults folder. I was unaware it was going to be blocks as well.

**Comment by MightyGorgon** [comment]
You are right, there was a bug on my plugins install generation... I'll fix it. :-)
